#!/bin/bash

#apt-get clean
#apt-get update
#apt-get install git

echo "Hello. This is setup."

# Give me number of cores avail!
cores=$(nproc)
echo "Number of processor cores: ${cores}"

# Debug disk space.
echo "Checking disk space."
df -h

echo "Setting hostname."
echo opm > /etc/hostname

echo "Setting gpu_mem."
if grep -q "gpu_mem" /boot/config.txt
then
    sed -i "s/gpu_mem.*/gpu_mem=256/" /boot/config.txt
else
    echo "gpu_mem=256" >> /boot/config.txt
fi

echo "Installing packages."
apt-get -y update
apt-get -y install git

echo "Downloading openFrameworks."
cd /home/pi
wget http://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linuxarmv6l_release.tar.gz
mkdir openFrameworks
tar vxfz of_v0.9.8_linuxarmv6l_release.tar.gz -C openFrameworks --strip-components 1
cd /home/pi/openFrameworks/scripts/linux/debian

# This is needed to install everything automatically
sed -i "s/apt-get/apt-get -y/g" install_dependencies.sh

./install_dependencies.sh
make -j$(nproc) Release -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project
cd /home/pi/openFrameworks/examples/graphics/polygonExample
make -j$(nproc)

echo "Setting up to run on boot."
crontab -l > mycron
echo "@reboot /home/pi/openFrameworks/examples/graphics/polygonExample/bin/polygonExample" >> mycron
crontab mycron
rm mycron
